import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai"

import { Inter } from '@next/font/google'

import Image from 'next/image';
import sumit from '../styles/sumitc.png';
import code from '../styles/code.png';
import HCJ from '../public/HCJ logo.png';
import react from '../public/react logo.png'
import next from '../public/nextjs.png'
import Tail from '../public/tail.png'
//swiper
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

//autoslide
import SwiperCore ,{Autoplay} from 'swiper';

//import potfolio photos
import Dyna from '../public/Dyna.png';
import Users from '../public/users.png';
import Cal from '../public/cal.png';
import Spo from '../public/spo.png'

//dark mode
import { useState } from 'react';

import Link from 'next/link';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode]= useState(false);
  SwiperCore.use([Autoplay])

  return (
    <div className={darkMode ? "dark":""}>
      <Head>
        <title>Sumit Mestry Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=' text-xl font-sans font-bold dark:text-white' >Developed by Sumit</h1>
            <ul className='flex items-center'>
              <li className=' cursor-pointer  text-2xl  dark:text-white'><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)}/></li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8  font-bold" href="https://i.ibb.co/N2dhM93/Sumit-Mestry.png">Resume</a></li>
            </ul>
          </nav>
          <div className=" text-center p-10 py-10">
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-300'>Sumit Mestry</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Front-end Developer</h3>
            <p className=' text-md py-5 leading-8  text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>Creative individual with
an ability to work under
pressure and meet
deadlines.
I am looking foward for
my first work experience
in IT industry.</p>
          </div>

          <div className=' flex text-5xl justify-center gap-16 py-3 text-gray-600  dark:text-teal-500'>
            <AiFillLinkedin/>
            <AiFillYoutube/>
            <AiFillTwitterCircle/>
          </div>
          <div className='relative  bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={sumit} />
          </div>
        </section>

        {/* end of first session */}
      
    <section>
        <div className='text-3xl py-1 md:text-4xl dark:text-white'><h2>Skills</h2></div>
    <div className='md:flex gap-10 '>
        <Swiper
      spaceBetween={50}
      slidesPerView={1.5}
      
      autoplay={{
        delay:2000
      }}
      >


      <SwiperSlide><div className=' text-center shadow-xl p-10 rounded-xl my-10  dark:bg-teal-100  ' >
      <div className='md:flex justify-evenly '>
              <Image src={react} width={150} height={100} class="h-auto max-w-full"/></div>
              <h3 className='text-lg font-semibold pt-4 pb-2 md:text-xl'>ReactJs</h3>
              <p className='py-2 '>Made 5+ projects using  <span className=' font-bold'>React leaflet</span>,Google Map API and React Hooks</p>
            </div></SwiperSlide>
      <SwiperSlide> <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-100 ' >
      <div className='md:flex justify-evenly'>
              <Image src={next} width={150} height={100} /></div>
              <h3 className='text-lg font-semibold pt-4 pb-2 md:text-xl'>Next.Js</h3>
              <p className='py-2 '>Portfolio Project and pursuing a in-depth  <span className=' font-bold'>course on Next.js</span> from Maximilian Schwarzmuller</p>
            </div></SwiperSlide>
      <SwiperSlide> <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-100 ' >
      <div className='md:flex justify-evenly'>
              <Image src={Tail} width={150} height={100} /></div>
              <h3 className='text-lg font-semibold pt-4 pb-2 md:text-xl'>Tailwind CSS</h3>
              <p className='py-2 '>Making Complex responsive layouts like <span className=' font-bold'>Dark mode</span> in an efficient way</p>
            </div></SwiperSlide>
      <SwiperSlide> <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-100 ' >
      <div className='md:flex justify-evenly'>
              <Image src={HCJ} width={150} height={100} /></div>
              <h3 className='text-lg font-semibold pt-4 pb-2 md:text-xl'>HTML, CSS, Javascript</h3>
              <p className='py-2 '>Clone of Iphone14 <span className=' font-bold'>Dynamic Island</span> and more Creative projects</p>
            </div></SwiperSlide>
      
      
    </Swiper>
    </div>   
  </section>
        <section>
          <div >
            <h3 className='text-3xl py-1 dark:text-white '>Projects</h3>
          </div>
        <div className='flex flex-col gap-10 py-10 md:flex-row md:flex-wrap hover:cursor-pointer'>
          <div className=' basis-1/3 flex-1' >
          <Link href="https://sumit-dynamic-island.netlify.app/">
            <Image src={Dyna} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout={"responsive"}></Image></Link>
          </div>

          <div className=' basis-1/3 flex-1'>
          <Link href="https://www.youtube.com/watch?v=pyENT11cOiE">
            <Image src={Users} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout={"responsive"}></Image></Link>
          </div>

          <div className=' basis-1/3 flex-1'>
          <Link href="https://sumitcalculator.netlify.app/">
            <Image src={Cal} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout={"responsive"}></Image></Link>
          </div>
          <div className=' basis-1/3 flex-1'>
            <Image src={Spo} className="rounded-lg object-cover " width={'100%'} height={'100%'} layout={"responsive"}></Image>
          </div>
          </div>
        </section>
       
      </main>
    </div>
  )
}
